export default [
  {
  login: "mdc-17",
  id: 59869592,
  node_id: "MDQ6VXNlcjU5ODY5NTky",
  avatar_url: "https://avatars.githubusercontent.com/u/59869592?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/mdc-17",
  html_url: "https://github.com/mdc-17",
  followers_url: "https://api.github.com/users/mdc-17/followers",
  following_url: "https://api.github.com/users/mdc-17/following{/other_user}",
  gists_url: "https://api.github.com/users/mdc-17/gists{/gist_id}",
  starred_url: "https://api.github.com/users/mdc-17/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/mdc-17/subscriptions",
  organizations_url: "https://api.github.com/users/mdc-17/orgs",
  repos_url: "https://api.github.com/users/mdc-17/repos",
  events_url: "https://api.github.com/users/mdc-17/events{/privacy}",
  received_events_url: "https://api.github.com/users/mdc-17/received_events",
  type: "User",
  site_admin: false
  },
  {
  login: "AmaliaGlez",
  id: 60327195,
  node_id: "MDQ6VXNlcjYwMzI3MTk1",
  avatar_url: "https://avatars.githubusercontent.com/u/60327195?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/AmaliaGlez",
  html_url: "https://github.com/AmaliaGlez",
  followers_url: "https://api.github.com/users/AmaliaGlez/followers",
  following_url: "https://api.github.com/users/AmaliaGlez/following{/other_user}",
  gists_url: "https://api.github.com/users/AmaliaGlez/gists{/gist_id}",
  starred_url: "https://api.github.com/users/AmaliaGlez/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/AmaliaGlez/subscriptions",
  organizations_url: "https://api.github.com/users/AmaliaGlez/orgs",
  repos_url: "https://api.github.com/users/AmaliaGlez/repos",
  events_url: "https://api.github.com/users/AmaliaGlez/events{/privacy}",
  received_events_url: "https://api.github.com/users/AmaliaGlez/received_events",
  type: "User",
  site_admin: false
  },
  {
  login: "denyscodes",
  id: 32089750,
  node_id: "MDQ6VXNlcjMyMDg5NzUw",
  avatar_url: "https://avatars.githubusercontent.com/u/32089750?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/denyscodes",
  html_url: "https://github.com/denyscodes",
  followers_url: "https://api.github.com/users/denyscodes/followers",
  following_url: "https://api.github.com/users/denyscodes/following{/other_user}",
  gists_url: "https://api.github.com/users/denyscodes/gists{/gist_id}",
  starred_url: "https://api.github.com/users/denyscodes/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/denyscodes/subscriptions",
  organizations_url: "https://api.github.com/users/denyscodes/orgs",
  repos_url: "https://api.github.com/users/denyscodes/repos",
  events_url: "https://api.github.com/users/denyscodes/events{/privacy}",
  received_events_url: "https://api.github.com/users/denyscodes/received_events",
  type: "User",
  site_admin: false
  },
  {
  login: "DouaeSAMI",
  id: 72701638,
  node_id: "MDQ6VXNlcjcyNzAxNjM4",
  avatar_url: "https://avatars.githubusercontent.com/u/72701638?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/DouaeSAMI",
  html_url: "https://github.com/DouaeSAMI",
  followers_url: "https://api.github.com/users/DouaeSAMI/followers",
  following_url: "https://api.github.com/users/DouaeSAMI/following{/other_user}",
  gists_url: "https://api.github.com/users/DouaeSAMI/gists{/gist_id}",
  starred_url: "https://api.github.com/users/DouaeSAMI/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/DouaeSAMI/subscriptions",
  organizations_url: "https://api.github.com/users/DouaeSAMI/orgs",
  repos_url: "https://api.github.com/users/DouaeSAMI/repos",
  events_url: "https://api.github.com/users/DouaeSAMI/events{/privacy}",
  received_events_url: "https://api.github.com/users/DouaeSAMI/received_events",
  type: "User",
  site_admin: false
  },
  {
  login: "rUKAoss",
  id: 74503773,
  node_id: "MDQ6VXNlcjc0NTAzNzcz",
  avatar_url: "https://avatars.githubusercontent.com/u/74503773?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/rUKAoss",
  html_url: "https://github.com/rUKAoss",
  followers_url: "https://api.github.com/users/rUKAoss/followers",
  following_url: "https://api.github.com/users/rUKAoss/following{/other_user}",
  gists_url: "https://api.github.com/users/rUKAoss/gists{/gist_id}",
  starred_url: "https://api.github.com/users/rUKAoss/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/rUKAoss/subscriptions",
  organizations_url: "https://api.github.com/users/rUKAoss/orgs",
  repos_url: "https://api.github.com/users/rUKAoss/repos",
  events_url: "https://api.github.com/users/rUKAoss/events{/privacy}",
  received_events_url: "https://api.github.com/users/rUKAoss/received_events",
  type: "User",
  site_admin: false
  }
  ]
