export default {
	login: 'victorronda',
	id: 60758125,
	node_id: 'MDQ6VXNlcjYwNzU4MTI1',
	avatar_url: 'https://avatars.githubusercontent.com/u/60758125?v=4',
	gravatar_id: '',
	url: 'https://api.github.com/users/victorronda',
	html_url: 'https://github.com/victorronda',
	followers_url: 'https://api.github.com/users/victorronda/followers',
	following_url: 'https://api.github.com/users/victorronda/following{/other_user}',
	gists_url: 'https://api.github.com/users/victorronda/gists{/gist_id}',
	starred_url: 'https://api.github.com/users/victorronda/starred{/owner}{/repo}',
	subscriptions_url: 'https://api.github.com/users/victorronda/subscriptions',
	organizations_url: 'https://api.github.com/users/victorronda/orgs',
	repos_url: 'https://api.github.com/users/victorronda/repos',
	events_url: 'https://api.github.com/users/victorronda/events{/privacy}',
	received_events_url: 'https://api.github.com/users/victorronda/received_events',
	type: 'User',
	site_admin: false,
	name: 'Victor Ronda',
	company: null,
	blog: '',
	location: 'Barcelona, Spain',
	email: null,
	hireable: true,
	bio: 'I just finished a Web Developer bootcamp at Ironhack. Ready to create awesome web sites',
	twitter_username: 'victor_ronda',
	public_repos: 48,
	public_gists: 1,
	followers: 5,
	following: 22,
	created_at: '2020-02-06T20:59:32Z',
	updated_at: '2021-01-27T15:02:20Z'
};
